on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - master
jobs:
  Run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          printenv
